services:
  db:
    container_name: postgres_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_playground
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U django_user -d django_playground']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_web
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  web:
    container_name: django_web
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend_react
    image: node:20-alpine
    working_dir: /app
    command: sh -c "corepack enable && pnpm install && pnpm dev --host 0.0.0.0"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_pnpm_cache:/app/.pnpm-store
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
  pgadmin_data:
  frontend_node_modules:
  frontend_pnpm_cache:
